/**
 * MCP-014 — Referee feedback banner library: the hand-authored string library.
 *
 * `REFEREE_BANNER_LIBRARY` is the >=103-entry banner library (MCP-008 §5.1
 * category floors). Every entry describes a STRUCTURAL play property of the
 * MOVE — never the person, never a verdict. Each entry's `accessibilityLabel`
 * is produced by `buildBannerAccessibilityLabel` at module load so the label
 * can never drift from the headline.
 *
 * Pure TypeScript. No network. No Supabase. No React. No runtime cross-feature
 * import except the local `accessibilityLabel` helper.
 *
 * Doctrine (MCP-014 design § "Doctrine self-check"):
 *   - No banner string carries a verdict / winner / loser / truth / person
 *     label / popularity-praise token (enforced by `refereeBannerBanList`).
 *   - Every celebratory / confident banner that could over-claim on a
 *     low-confidence signal has a softened `*_soft` sibling whose headline
 *     hedges (`looks like` / `might` / `reads as` / `may`).
 *   - Softened siblings have `minConfidence: 'low'` and
 *     `softenedSiblingCode: null` — no infinite chain.
 *   - `contains_unplayable_insult_only` is intentionally silent — the move is
 *     never labelled "an insult" (`INTENTIONALLY_SILENT_CLASSIFIERS`).
 */

import { buildBannerAccessibilityLabel } from './accessibilityLabel';
import type { RefereeBanner } from './types';
import type { SemanticClassifierId } from '../semanticReferee/semanticRefereeTypes';

/**
 * The internal authoring shape — every field of `RefereeBanner` EXCEPT
 * `accessibilityLabel`, which is generated from `headline` + `helperLine` +
 * `tone` so the label can never drift from the visible copy.
 */
type RefereeBannerSeed = Omit<RefereeBanner, 'accessibilityLabel'>;

/**
 * The 103 hand-authored banner seeds. Authored by category, in
 * `BANNER_CATEGORY_PRIORITY`-irrelevant order (selection priority lives in
 * `selectBanner.ts`). Each category meets its MCP-008 §5.1 floor:
 *   continuity 10 · evidence_debt 9 · hot_take 9 · clever_rebuttal 9 ·
 *   source_chain_gap 9 · branch_suggestion 8 · tangent_suggestion 8 ·
 *   synthesis_readiness 9 · quote_needed 8 · mechanism_needed 8 ·
 *   mode_mismatch 8 · pacing_cooldown 8  = 103.
 */
const BANNER_SEEDS: readonly RefereeBannerSeed[] = [
  // ── continuity (10) ────────────────────────────────────────────
  {
    bannerCode: 'continuity_clean_tie',
    category: 'continuity',
    tone: 'celebratory',
    headline: 'Clean parent tie.',
    helperLine: 'This picks up the thread the parent left open.',
    toneGlyph: 'star',
    minConfidence: 'high',
    softenedSiblingCode: 'continuity_clean_tie_soft',
  },
  {
    bannerCode: 'continuity_clean_tie_soft',
    category: 'continuity',
    tone: 'nudge',
    headline: 'This looks like it ties to the parent.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'continuity_engages_mechanism',
    category: 'continuity',
    tone: 'celebratory',
    headline: 'Good — this engages the actual point above.',
    toneGlyph: 'star',
    minConfidence: 'high',
    softenedSiblingCode: 'continuity_engages_mechanism_soft',
  },
  {
    bannerCode: 'continuity_engages_mechanism_soft',
    category: 'continuity',
    tone: 'nudge',
    headline: 'This may be engaging the point above.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'continuity_answers_question',
    category: 'continuity',
    tone: 'celebratory',
    headline: 'That answers the question on the table.',
    toneGlyph: 'star',
    minConfidence: 'medium',
    softenedSiblingCode: 'continuity_answers_question_soft',
  },
  {
    bannerCode: 'continuity_answers_question_soft',
    category: 'continuity',
    tone: 'nudge',
    headline: 'This reads as an answer to the open question.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'continuity_picks_up_thread',
    category: 'continuity',
    tone: 'celebratory',
    headline: 'Nice — the thread keeps moving here.',
    toneGlyph: 'star',
    minConfidence: 'medium',
    softenedSiblingCode: 'continuity_picks_up_thread_soft',
  },
  {
    bannerCode: 'continuity_picks_up_thread_soft',
    category: 'continuity',
    tone: 'nudge',
    headline: 'This looks like it keeps the thread moving.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'continuity_clarification_landed',
    category: 'continuity',
    tone: 'celebratory',
    headline: "Good — that clears up what's being argued.",
    toneGlyph: 'star',
    minConfidence: 'medium',
    softenedSiblingCode: 'continuity_clarification_landed_soft',
  },
  {
    bannerCode: 'continuity_clarification_landed_soft',
    category: 'continuity',
    tone: 'nudge',
    headline: 'This may help clear up what is being argued.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },

  // ── evidence_debt (9) ──────────────────────────────────────────
  {
    bannerCode: 'evidence_debt_opened',
    category: 'evidence_debt',
    tone: 'nudge',
    headline: 'Good pressure — an evidence debt opened.',
    helperLine: 'A source closes it.',
    toneGlyph: 'arrow',
    minConfidence: 'medium',
    softenedSiblingCode: 'evidence_debt_opened_soft',
  },
  {
    bannerCode: 'evidence_debt_opened_soft',
    category: 'evidence_debt',
    tone: 'nudge',
    headline: 'This might open an evidence debt.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'evidence_debt_resolved',
    category: 'evidence_debt',
    tone: 'celebratory',
    headline: 'Evidence debt resolved — nice.',
    toneGlyph: 'star',
    minConfidence: 'high',
    softenedSiblingCode: 'evidence_debt_resolved_soft',
  },
  {
    bannerCode: 'evidence_debt_resolved_soft',
    category: 'evidence_debt',
    tone: 'nudge',
    headline: 'This looks like it resolves an evidence debt.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'evidence_debt_source_attached',
    category: 'evidence_debt',
    tone: 'celebratory',
    headline: 'Source attached — that backs the claim.',
    toneGlyph: 'star',
    minConfidence: 'medium',
    softenedSiblingCode: 'evidence_debt_source_attached_soft',
  },
  {
    bannerCode: 'evidence_debt_source_attached_soft',
    category: 'evidence_debt',
    tone: 'nudge',
    headline: 'A source may be attached to this claim.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'evidence_debt_connect_it',
    category: 'evidence_debt',
    tone: 'nudge',
    headline: 'Evidence is here — connect it to the exact claim.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'evidence_debt_open_still',
    category: 'evidence_debt',
    tone: 'nudge',
    headline: 'A source is still open on this point.',
    helperLine: 'Adding one closes the loop.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'evidence_debt_a_source_would_help',
    category: 'evidence_debt',
    tone: 'nudge',
    headline: 'A source would carry this point further.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },

  // ── hot_take (9) ───────────────────────────────────────────────
  {
    bannerCode: 'hot_take_playable',
    category: 'hot_take',
    tone: 'celebratory',
    headline: 'Bold move — and it stays playable.',
    helperLine: 'It gives the other side something to engage.',
    toneGlyph: 'star',
    minConfidence: 'medium',
    softenedSiblingCode: 'hot_take_playable_soft',
  },
  {
    bannerCode: 'hot_take_playable_soft',
    category: 'hot_take',
    tone: 'nudge',
    headline: 'This reads as a bold but playable move.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'hot_take_has_an_edge',
    category: 'hot_take',
    tone: 'celebratory',
    headline: 'This has an edge — and a foothold to reply to.',
    toneGlyph: 'star',
    minConfidence: 'medium',
    softenedSiblingCode: 'hot_take_has_an_edge_soft',
  },
  {
    bannerCode: 'hot_take_has_an_edge_soft',
    category: 'hot_take',
    tone: 'nudge',
    headline: 'This may have an edge worth replying to.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'hot_take_coherent',
    category: 'hot_take',
    tone: 'celebratory',
    headline: 'Strong take — it holds together.',
    toneGlyph: 'star',
    minConfidence: 'medium',
    softenedSiblingCode: 'hot_take_coherent_soft',
  },
  {
    bannerCode: 'hot_take_coherent_soft',
    category: 'hot_take',
    tone: 'nudge',
    headline: 'This take looks like it holds together.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'hot_take_invites_a_reply',
    category: 'hot_take',
    tone: 'nudge',
    headline: 'A spicy take — it invites a real reply.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'hot_take_room_can_engage',
    category: 'hot_take',
    tone: 'nudge',
    headline: 'Sharp angle — the room has something to engage.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'hot_take_keeps_it_about_the_claim',
    category: 'hot_take',
    tone: 'nudge',
    headline: 'A bold claim that stays about the claim.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },

  // ── clever_rebuttal (9) ────────────────────────────────────────
  {
    bannerCode: 'clever_rebuttal_sharp_counter',
    category: 'clever_rebuttal',
    tone: 'celebratory',
    headline: 'Sharp counter — it lands on the point.',
    toneGlyph: 'star',
    minConfidence: 'high',
    softenedSiblingCode: 'clever_rebuttal_sharp_counter_soft',
  },
  {
    bannerCode: 'clever_rebuttal_sharp_counter_soft',
    category: 'clever_rebuttal',
    tone: 'nudge',
    headline: 'This reads as a sharp counter.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'clever_rebuttal_anchored',
    category: 'clever_rebuttal',
    tone: 'celebratory',
    headline: 'Nicely anchored to their words.',
    toneGlyph: 'star',
    minConfidence: 'medium',
    softenedSiblingCode: 'clever_rebuttal_anchored_soft',
  },
  {
    bannerCode: 'clever_rebuttal_anchored_soft',
    category: 'clever_rebuttal',
    tone: 'nudge',
    headline: 'This may be anchored to their words.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'clever_rebuttal_finds_the_seam',
    category: 'clever_rebuttal',
    tone: 'celebratory',
    headline: 'Good eye — this finds the seam in the claim.',
    toneGlyph: 'star',
    minConfidence: 'medium',
    softenedSiblingCode: 'clever_rebuttal_finds_the_seam_soft',
  },
  {
    bannerCode: 'clever_rebuttal_finds_the_seam_soft',
    category: 'clever_rebuttal',
    tone: 'nudge',
    headline: 'This might find the seam in the claim.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'clever_rebuttal_counterexample',
    category: 'clever_rebuttal',
    tone: 'nudge',
    headline: 'A counterexample — it tests the claim directly.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'clever_rebuttal_tight_pressure',
    category: 'clever_rebuttal',
    tone: 'nudge',
    headline: 'Tight pressure — the claim has to answer this.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'clever_rebuttal_names_the_gap',
    category: 'clever_rebuttal',
    tone: 'nudge',
    headline: 'Clear pushback — it names where the claim falls short.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },

  // ── source_chain_gap (9) ───────────────────────────────────────
  {
    bannerCode: 'source_chain_gap_popularity_not_proof',
    category: 'source_chain_gap',
    tone: 'nudge',
    headline: "Popularity isn't proof — what's the source?",
    helperLine: 'A primary source moves this onto solid ground.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'source_chain_gap_trace_it_back',
    category: 'source_chain_gap',
    tone: 'nudge',
    headline: 'Where did this come from? Trace it back a step.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'source_chain_gap_chain_breaks',
    category: 'source_chain_gap',
    tone: 'nudge',
    headline: 'The source trail has a gap — name the origin.',
    toneGlyph: 'arrow',
    minConfidence: 'medium',
    softenedSiblingCode: 'source_chain_gap_chain_breaks_soft',
  },
  {
    bannerCode: 'source_chain_gap_chain_breaks_soft',
    category: 'source_chain_gap',
    tone: 'nudge',
    headline: 'The source trail may have a gap here.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'source_chain_gap_retraction_noted',
    category: 'source_chain_gap',
    tone: 'nudge',
    headline: 'This cites a retraction — worth flagging the chain.',
    toneGlyph: 'arrow',
    minConfidence: 'medium',
    softenedSiblingCode: 'source_chain_gap_retraction_noted_soft',
  },
  {
    bannerCode: 'source_chain_gap_retraction_noted_soft',
    category: 'source_chain_gap',
    tone: 'nudge',
    headline: 'This may be pointing at a retracted source.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'source_chain_gap_satire_not_evidence',
    category: 'source_chain_gap',
    tone: 'nudge',
    headline: 'Satire is not evidence — a real source helps here.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'source_chain_gap_ask_for_origin',
    category: 'source_chain_gap',
    tone: 'nudge',
    headline: 'Ask for the origin before this carries weight.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'source_chain_gap_one_more_link',
    category: 'source_chain_gap',
    tone: 'nudge',
    headline: 'One more link would close the source trail.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },

  // ── branch_suggestion (8) ──────────────────────────────────────
  {
    bannerCode: 'branch_belongs_on_branch',
    category: 'branch_suggestion',
    tone: 'routing_hint',
    headline: 'This probably belongs on a branch.',
    helperLine: 'A side branch keeps the main thread readable.',
    toneGlyph: 'branch',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'branch_clean_branch',
    category: 'branch_suggestion',
    tone: 'celebratory',
    headline: 'Clean branch — both threads stay readable.',
    toneGlyph: 'star',
    minConfidence: 'medium',
    softenedSiblingCode: 'branch_clean_branch_soft',
  },
  {
    bannerCode: 'branch_clean_branch_soft',
    category: 'branch_suggestion',
    tone: 'nudge',
    headline: 'This looks like a clean branch.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'branch_new_voice_welcome',
    category: 'branch_suggestion',
    tone: 'routing_hint',
    headline: 'A new voice on the same topic — a chime-in branch fits.',
    toneGlyph: 'branch',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'branch_side_issue_home',
    category: 'branch_suggestion',
    tone: 'routing_hint',
    headline: 'A side branch is a tidy home for this.',
    toneGlyph: 'branch',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'branch_keeps_mainline_clear',
    category: 'branch_suggestion',
    tone: 'routing_hint',
    headline: 'Branch this — the main line stays clear.',
    toneGlyph: 'branch',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'branch_two_threads_at_once',
    category: 'branch_suggestion',
    tone: 'routing_hint',
    headline: 'Two threads at once — a branch separates them.',
    toneGlyph: 'branch',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'branch_open_it_on_the_side',
    category: 'branch_suggestion',
    tone: 'routing_hint',
    headline: 'Open this on the side without losing the thread.',
    toneGlyph: 'branch',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },

  // ── tangent_suggestion (8) ─────────────────────────────────────
  {
    bannerCode: 'tangent_new_issue_here',
    category: 'tangent_suggestion',
    tone: 'routing_hint',
    headline: 'This opens a new issue — a tangent keeps it tidy.',
    helperLine: 'The point above is still waiting for a reply.',
    toneGlyph: 'branch',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'tangent_drifts_from_parent',
    category: 'tangent_suggestion',
    tone: 'routing_hint',
    headline: 'This drifts from the point above — try a side issue.',
    toneGlyph: 'branch',
    minConfidence: 'medium',
    softenedSiblingCode: 'tangent_drifts_from_parent_soft',
  },
  {
    bannerCode: 'tangent_drifts_from_parent_soft',
    category: 'tangent_suggestion',
    tone: 'routing_hint',
    headline: 'This may be drifting from the point above.',
    toneGlyph: 'branch',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'tangent_different_axis',
    category: 'tangent_suggestion',
    tone: 'routing_hint',
    headline: 'A different axis than the one above — a tangent fits.',
    toneGlyph: 'branch',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'tangent_park_it_alongside',
    category: 'tangent_suggestion',
    tone: 'routing_hint',
    headline: 'Park this alongside the main thread as a tangent.',
    toneGlyph: 'branch',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'tangent_worth_its_own_lane',
    category: 'tangent_suggestion',
    tone: 'routing_hint',
    headline: 'Worth its own lane — a tangent keeps both readable.',
    toneGlyph: 'branch',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'tangent_fresh_thread_reads_clearer',
    category: 'tangent_suggestion',
    tone: 'routing_hint',
    headline: 'A fresh thread reads clearer for this one.',
    toneGlyph: 'branch',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'tangent_side_trip_keeps_focus',
    category: 'tangent_suggestion',
    tone: 'routing_hint',
    headline: 'A side trip here keeps the main point in focus.',
    toneGlyph: 'branch',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },

  // ── synthesis_readiness (9) ────────────────────────────────────
  {
    bannerCode: 'synthesis_shared_ground_named',
    category: 'synthesis_readiness',
    tone: 'celebratory',
    headline: 'Shared ground named — nice synthesis.',
    toneGlyph: 'star',
    minConfidence: 'high',
    softenedSiblingCode: 'synthesis_shared_ground_named_soft',
  },
  {
    bannerCode: 'synthesis_shared_ground_named_soft',
    category: 'synthesis_readiness',
    tone: 'nudge',
    headline: 'This reads as naming shared ground.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'synthesis_almost_there',
    category: 'synthesis_readiness',
    tone: 'nudge',
    headline: 'Almost a synthesis — name the shared point.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'synthesis_sides_converging',
    category: 'synthesis_readiness',
    tone: 'celebratory',
    headline: 'The two sides are converging here.',
    toneGlyph: 'star',
    minConfidence: 'medium',
    softenedSiblingCode: 'synthesis_sides_converging_soft',
  },
  {
    bannerCode: 'synthesis_sides_converging_soft',
    category: 'synthesis_readiness',
    tone: 'nudge',
    headline: 'The two sides may be converging here.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'synthesis_narrow_concession_noted',
    category: 'synthesis_readiness',
    tone: 'celebratory',
    headline: 'Narrow concession noted — the broad point still stands.',
    toneGlyph: 'star',
    minConfidence: 'medium',
    softenedSiblingCode: 'synthesis_narrow_concession_noted_soft',
  },
  {
    bannerCode: 'synthesis_narrow_concession_noted_soft',
    category: 'synthesis_readiness',
    tone: 'nudge',
    headline: 'This may be a narrow concession that keeps the broad point.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'synthesis_nice_narrowing',
    category: 'synthesis_readiness',
    tone: 'celebratory',
    headline: 'Nice narrowing — the broader point holds.',
    toneGlyph: 'star',
    minConfidence: 'medium',
    softenedSiblingCode: 'synthesis_nice_narrowing_soft',
  },
  {
    bannerCode: 'synthesis_nice_narrowing_soft',
    category: 'synthesis_readiness',
    tone: 'nudge',
    headline: 'This looks like a narrowing that keeps the broader point.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },

  // ── quote_needed (8) ───────────────────────────────────────────
  {
    bannerCode: 'quote_needed_exact_excerpt',
    category: 'quote_needed',
    tone: 'nudge',
    headline: 'Source is here — the exact quote is still needed.',
    helperLine: 'Pulling the passage anchors the point.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'quote_needed_pin_the_passage',
    category: 'quote_needed',
    tone: 'nudge',
    headline: 'Pin the exact passage you mean.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'quote_needed_which_line',
    category: 'quote_needed',
    tone: 'nudge',
    headline: 'Which line in the source? Quote it directly.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'quote_needed_anchor_to_their_words',
    category: 'quote_needed',
    tone: 'nudge',
    headline: 'Anchor this to their exact words.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'quote_needed_paraphrase_only',
    category: 'quote_needed',
    tone: 'nudge',
    headline: 'A paraphrase so far — the quoted text would help.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'quote_needed_ask_for_quote',
    category: 'quote_needed',
    tone: 'nudge',
    headline: 'Ask for the exact quote before building on it.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'quote_needed_show_the_words',
    category: 'quote_needed',
    tone: 'nudge',
    headline: 'Show the words — a quote makes this concrete.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'quote_needed_excerpt_anchors_it',
    category: 'quote_needed',
    tone: 'nudge',
    headline: 'An excerpt would anchor this to the source.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },

  // ── mechanism_needed (8) ───────────────────────────────────────
  {
    bannerCode: 'mechanism_needed_how_does_it_work',
    category: 'mechanism_needed',
    tone: 'nudge',
    headline: 'How does this work? Name the mechanism.',
    helperLine: 'Spelling out the steps makes the point land.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'mechanism_needed_connect_cause_effect',
    category: 'mechanism_needed',
    tone: 'nudge',
    headline: 'Connect the cause to the effect here.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'mechanism_needed_why_does_that_follow',
    category: 'mechanism_needed',
    tone: 'nudge',
    headline: 'Why does that follow? Show the link.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'mechanism_needed_steps_are_missing',
    category: 'mechanism_needed',
    tone: 'nudge',
    headline: 'A step is missing between the claim and the result.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'mechanism_needed_spell_out_the_chain',
    category: 'mechanism_needed',
    tone: 'nudge',
    headline: 'Spell out the chain from premise to conclusion.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'mechanism_needed_what_drives_it',
    category: 'mechanism_needed',
    tone: 'nudge',
    headline: 'What drives this outcome? Name it.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'mechanism_needed_logic_gap',
    category: 'mechanism_needed',
    tone: 'nudge',
    headline: 'There is a gap in the logic — fill it in.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'mechanism_needed_show_the_working',
    category: 'mechanism_needed',
    tone: 'nudge',
    headline: 'Show the working behind this claim.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },

  // ── mode_mismatch (8) ──────────────────────────────────────────
  {
    bannerCode: 'mode_mismatch_register_off',
    category: 'mode_mismatch',
    tone: 'nudge',
    headline: 'This reads off-register for the room.',
    helperLine: 'A small tweak fits it to the room mode.',
    toneGlyph: 'arrow',
    minConfidence: 'medium',
    softenedSiblingCode: 'mode_mismatch_register_off_soft',
  },
  {
    bannerCode: 'mode_mismatch_register_off_soft',
    category: 'mode_mismatch',
    tone: 'nudge',
    headline: 'This may read off-register for the room.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'mode_mismatch_fits_the_room',
    category: 'mode_mismatch',
    tone: 'celebratory',
    headline: 'Fits the room.',
    toneGlyph: 'star',
    minConfidence: 'medium',
    softenedSiblingCode: 'mode_mismatch_fits_the_room_soft',
  },
  {
    bannerCode: 'mode_mismatch_fits_the_room_soft',
    category: 'mode_mismatch',
    tone: 'nudge',
    headline: 'This looks like it fits the room.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'mode_mismatch_check_the_mode',
    category: 'mode_mismatch',
    tone: 'nudge',
    headline: 'Check the room mode — this move type may not fit.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'mode_mismatch_room_expects_more_structure',
    category: 'mode_mismatch',
    tone: 'nudge',
    headline: 'This room expects a bit more structure here.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'mode_mismatch_tone_for_a_casual_room',
    category: 'mode_mismatch',
    tone: 'nudge',
    headline: 'This room runs casual — a lighter tone fits.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'mode_mismatch_match_the_room_style',
    category: 'mode_mismatch',
    tone: 'nudge',
    headline: 'A small tweak matches this to the room style.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },

  // ── pacing_cooldown (8) ────────────────────────────────────────
  {
    bannerCode: 'pacing_you_decide_the_lane',
    category: 'pacing_cooldown',
    tone: 'routing_hint',
    headline: 'Reply here, branch, or tangent? — you decide.',
    helperLine: 'The two signals point different ways — your call.',
    toneGlyph: 'branch',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'pacing_take_a_short_pause',
    category: 'pacing_cooldown',
    tone: 'nudge',
    headline: 'A short pause helps before the next move.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'pacing_is_on_in_this_room',
    category: 'pacing_cooldown',
    tone: 'nudge',
    headline: 'Pacing is on in this room — a short pause helps.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'pacing_let_the_reply_land',
    category: 'pacing_cooldown',
    tone: 'nudge',
    headline: 'Let the last reply land before the next one.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'pacing_room_for_the_other_side',
    category: 'pacing_cooldown',
    tone: 'nudge',
    headline: 'Leave room for the other side to respond.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'pacing_cooldown_is_active',
    category: 'pacing_cooldown',
    tone: 'nudge',
    headline: 'A short cooldown is on — the next move is soon.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'pacing_one_move_at_a_time',
    category: 'pacing_cooldown',
    tone: 'nudge',
    headline: 'One move at a time keeps the thread followable.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
  {
    bannerCode: 'pacing_a_pause_before_sending',
    category: 'pacing_cooldown',
    tone: 'nudge',
    headline: 'A pause before sending is worth it here.',
    toneGlyph: 'arrow',
    minConfidence: 'low',
    softenedSiblingCode: null,
  },
];

/**
 * The frozen banner library. Each entry's `accessibilityLabel` is generated
 * from `headline` + `helperLine` + `tone` at module load by
 * `buildBannerAccessibilityLabel` — so the label can never drift from the
 * visible copy. Every entry is `Object.freeze`d.
 */
export const REFEREE_BANNER_LIBRARY: ReadonlyArray<RefereeBanner> = Object.freeze(
  BANNER_SEEDS.map((seed) =>
    Object.freeze({
      ...seed,
      accessibilityLabel: buildBannerAccessibilityLabel(seed),
    }),
  ),
);

/** O(1) lookup index — `bannerCode` → `RefereeBanner`. */
export const BANNER_BY_CODE: ReadonlyMap<string, RefereeBanner> = (() => {
  const map = new Map<string, RefereeBanner>();
  for (const banner of REFEREE_BANNER_LIBRARY) {
    map.set(banner.bannerCode, banner);
  }
  return map;
})();

/**
 * Classifier ids whose presence is a ROUTING signal, not user feedback —
 * surfacing a banner for one would label the move punitively. Catalog v0 has
 * exactly one: `contains_unplayable_insult_only`. Its `CLASSIFIER_TO_BANNERS`
 * mapping is `[]`. A deliberate silence is distinguishable from a missing
 * mapping because this set is asserted exact by `refereeBannerLibrary.test.ts`.
 */
export const INTENTIONALLY_SILENT_CLASSIFIERS: ReadonlySet<SemanticClassifierId> =
  new Set<SemanticClassifierId>(['contains_unplayable_insult_only']);
