/**
 * Builds and writes the run log for a bot fixture scenario. CommonJS.
 */
const fs = require('node:fs');
const path = require('node:path');

const SECRET_RE_LIST = [
  /eyJ[A-Za-z0-9_-]{10,}/g,
  /sb_secret_[A-Za-z0-9_-]+/g,
  /sk-[A-Za-z0-9_-]+/g,
  /\b[A-Z0-9]{32,}\b/g,
];

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function redactText(text, aliasByEmail = {}) {
  let s = text;
  for (const [email, alias] of Object.entries(aliasByEmail)) {
    const re = new RegExp(escapeRe(email), 'gi');
    s = s.replace(re, `<${alias}>`);
  }
  for (const re of SECRET_RE_LIST) {
    s = s.replace(re, '[redacted]');
  }
  s = s.replace(/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g, '<email>');
  return s;
}

function formatMoveResultsTable(results) {
  const header =
    '| moveId | Expected | Actual | argumentId | Error | Detail |\n|---|---|---|---|---|---|';
  const rows = results.map((r) => {
    const detail = typeof r.errorDetail === 'string' && r.errorDetail.length > 0 ? r.errorDetail : '';
    return `| ${r.moveId} | ${r.expectedStatus || '—'} | ${r.actualStatus} | ${r.argumentId || '—'} | ${r.errorCode || ''} | ${detail} |`;
  });
  return [header, ...rows].join('\n');
}

function writeRunLog(input, outputDir) {
  const dir = outputDir || path.join(process.cwd(), 'docs', 'testing-runs');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const filename = `${input.dateIso.slice(0, 10)}-${input.scenarioId}.md`;
  const filePath = path.join(dir, filename);

  const body = [
    `# Bot fixture run — ${input.scenarioId} — ${input.dateIso.slice(0, 10)}`,
    '',
    'Generated by `scripts/bot-fixtures/runScenario.js`. Aliases only — no real emails or secrets.',
    '',
    '## Aliases',
    '',
    ...Object.values(input.aliasByEmail).map((a) => `- ${a}`),
    '',
    '## Argument Room',
    '',
    `- Room id: \`${input.roomId}\``,
    '',
    '## Move results',
    '',
    formatMoveResultsTable(input.results),
    '',
    '## Notes',
    '',
    input.notes,
    '',
    '## Secrets check',
    '',
    '- [x] No emails in plaintext',
    '- [x] No passwords in log',
    '- [x] No JWTs in log',
    '- [x] No service-role key used by runner',
    '',
  ].join('\n');

  const redacted = redactText(body, input.aliasByEmail);
  fs.writeFileSync(filePath, redacted);
  return filePath;
}

module.exports = { redactText, formatMoveResultsTable, writeRunLog };
