# One-shot script to create roadmap issues + add them to the Project.
$ErrorActionPreference = 'Stop'
$gh = "C:\Users\kyler\AppData\Local\Microsoft\WinGet\Packages\GitHub.cli_Microsoft.Winget.Source_8wekyb3d8bbwe\bin\gh.exe"
$projectNumber = 1
$projectOwner = "@me"

$cards = @(
    @{ code='TL-001'; title='Make Timeline the default room landing mode'; epic='epic:timeline'; priority='priority:p0'; effort='effort:m'; release='release:6.5'; goal='Change room default from Stack to Timeline. New rooms land on Timeline with the root selected. Stack remains a toggle, relabeled to Cards. Preserve active message across mode switches. needs_first_rebuttal gallery cards activate root; otherwise activate latest.'; accept='- Normal conversation opens in Timeline.|- Side rail collapsed on entry.|- Observer unless already a participant.|- Switching to Cards shows the same active message.|- Returning to Timeline preserves active node and scroll if possible.'; tests='roomEntryDefaultMode.test.ts -- non-participant, existing participant, new debate, no modal on entry.' },
    @{ code='TL-002'; title='Timeline onboarding focus on the first point'; epic='epic:timeline'; priority='priority:p0'; effort='effort:s'; release='release:6.5'; goal='Emphasize the first point so users understand the root claim before inspecting replies.'; accept='- First node has a Root marker.|- Root popover says This is the opening claim.|- Root -> first rebuttal edge uses distinct grammar (first clash).|- No-rebuttal rooms show Be the first rebuttal.|- Long timelines keep a Back to root control.'; tests='No-rebuttal card activates root; timeline renders root marker; root remains accessible after latest activation.' },
    @{ code='TL-003'; title='Timeline board shell with no page redirect'; epic='epic:timeline'; priority='priority:p0'; effort='effort:m'; release='release:6.5'; goal='Users should not go into or leave the timeline as a separate route. Timeline is the in-room board surface; tools open popovers, drawers, or sidecars in-place.'; accept='- All quick actions preserve current room.|- Stack/Cards toggle does not transition routes.|- Browser back does not strand a popover.'; tests='' },
    @{ code='VG-001'; title='Argument visual grammar: shape, color, weight, texture'; epic='epic:visual-grammar'; priority='priority:p0'; effort='effort:l'; release='release:6.5'; goal='Make timeline nodes self-explanatory: a glance distinguishes strong/weak, evidence-backed, source-chain pressure, concessions, tangents, hot zones.'; accept='- Shape never depends on color alone.|- Strong/weak shown through stroke, weight, texture.|- Evidence and source-chain pressure visually distinct.|- 44px min tap target.|- Accessibility labels describe node meaning.|- No truth/winner/loser copy.'; tests='Pure model maps argument type plus standing band to visual token; token has shape, color, stroke, accessibility label; no truth/winner/loser copy in tokens.' },
    @{ code='VG-002'; title='Gradient wave rail'; epic='epic:visual-grammar'; priority='priority:p0'; effort='effort:l'; release='release:6.6'; goal='Segmented gradient main rail that blends prior+next node colors, tone overlay, evidence-risk overlay, and active-path highlight.'; accept='- Active path glows.|- Strong evidence-backed path has clean saturated track.|- Tangent path kinks/breaks visibly.|- Hot unresolved segment is visually warm but never labeled correct or true.|- Legible at 250+ messages.|- No new dependencies (React Native primitives first).'; tests='' },
    @{ code='VG-003'; title='Bootstrap-inspired design tokens without importing Bootstrap'; epic='epic:visual-grammar'; priority='priority:p1'; effort='effort:m'; release='release:6.5'; goal='Use a Bootstrap-like consistency model (spacing scale, status badges, cards, pills, rails, popovers) WITHOUT adding Bootstrap as a dependency in the React Native app. Build a token layer: spacing.xs/s/m/l/xl, radius.sm/md/lg/pill, status.info/warning/danger/success/neutral, surface.base/elevated/overlay, rail.active/inactive, argument.claim/challenge/evidence/clarify/concede/branch.'; accept='- One source of tokens for timeline, side rail, sidecar, quick actions, profile popout.|- No new dependency unless a spike proves necessary.|- Web and mobile share naming even if platform rendering differs.'; tests='' },
    @{ code='BR-001'; title='Tangent kink model'; epic='epic:branches'; priority='priority:p0'; effort='effort:l'; release='release:6.6'; goal='Introduce kinks where a tangent leaves the main horizontal line and continues in its own lane. Mainline stays horizontal; first child continues on parent lane; additional children branch up or down.'; accept='- First child may stay on parent lane for mainline continuity.|- Additional children branch up/down.|- Source-chain / evidence branches get matching visual style.|- Collapse hides children but leaves a stub.|- Active node inside collapsed branch auto-expands or shows open branch.'; tests='Sibling branches get deterministic lanes; tangent creates kink edge; collapsed branch preserves count and stub; active branch path expands.' },
    @{ code='BR-002'; title='Split-screen branch inspector'; epic='epic:branches'; priority='priority:p2'; effort='effort:xl'; release='release:6.6'; goal='Inspect complex branches in a focused split view without leaving the room. Left: main timeline context. Right or bottom: branch timeline. Return to mainline CTA. No new route.'; accept='- User can inspect branch without leaving room.|- Branch preserves parent context.|- Sidecar updates to active node inside branch.'; tests='' },
    @{ code='SC-001'; title='Consolidate controls into the side action rail'; epic='epic:sidecar-rail'; priority='priority:p0'; effort='effort:l'; release='release:6.5'; goal='Rail is always available in Timeline mode, collapsed by default. Expanded set is grouped: Watch/Observe, Join side, Reply, Evidence, Branch, Review/flag, Share. Bubble tap updates active node and contextual rail actions.'; accept='- No required side declaration before entering.|- Join only triggered by explicit Join For / Join Against.|- No redirects.|- Own bubble safety: no edit/disagree/flag/score.|- Plain language only.'; tests='Observer rail collapsed; expands with join actions; participant other-bubble rail correct; own bubble safe.' },
    @{ code='SC-002'; title='Timeline node popover'; epic='epic:sidecar-rail'; priority='priority:p0'; effort='effort:m'; release='release:6.5'; goal='Tap a node to show a compact popover with the most important tools without forcing the full composer. Contents: preview, node type, strength band, tone/temperature, quick actions, Open details.'; accept='- Tap node activates state.|- Second tap / info icon opens popover.|- Popover does not block timeline nav.|- Same action mapping as side rail.|- Own node never exposes edit/disagree/flag/score.'; tests='Tapping node activates; popover shows correct allowed actions; own node restrictions enforced.' },
    @{ code='SC-003'; title='Sidecar as detail inspector, not action dumping ground'; epic='epic:sidecar-rail'; priority='priority:p1'; effort='effort:m'; release='release:6.6'; goal='Sidecar explains the selected message; the rail owns the main control surface. Sections: What this move says, Why it matters, What is unresolved, Where it sits, Suggested next move, Semantic flags (deeper in Stack mode).'; accept='- Timeline sidecar is concise.|- Stack sidecar exposes deeper semantic flags.|- No body editing.|- No internal snake_case codes leak to user.'; tests='' },
    @{ code='ST-001'; title='Reposition Stack as Card Details'; epic='epic:stack-detail'; priority='priority:p1'; effort='effort:s'; release='release:6.5'; goal='Make Stack mode clearly useful: it is not a competing main board, it is the deeper card inspection mode. Recommended labels: Timeline and Cards.'; accept='- Users understand why they would switch to Stack.|- Stack gives more detail than Timeline.|- Timeline remains primary.'; tests='Existing stack tests updated with new labels but kept passing.' },
    @{ code='ST-002'; title='Suggested reply flags per bubble card'; epic='epic:stack-detail'; priority='priority:p1'; effort='effort:m'; release='release:6.6'; goal='Each card suggests likely next moves: Source?, Quote?, Narrow, Counterexample, Define, Branch, Synthesize. Inputs: disagreement axis, sourceChainRisk, evidentiaryRisk, latest move type, active path depth, no-rebuttal state, stopReason, branch/tangent status, statement standing.'; accept='- Deterministic and explainable.|- Never blocks posting.|- Never labels people.|- Maps into quick-action presets.'; tests='' },
    @{ code='EV-001'; title='Evidence object model v1'; epic='epic:evidence'; priority='priority:p0'; effort='effort:l'; release='release:6.6'; goal='Turn evidence from a form field into a gameplay object: EvidenceArtifact { id, argumentId, kind (url|quote|source_text|dataset|screenshot_redacted|manual_citation), label, url?, sourceText?, quote?, sourceChainStatus, risk, addedByUserId, createdAt }.'; accept='- Evidence is attached to a move.|- Can be displayed as a receipt chip.|- Source-chain status visible on timeline node.|- Missing evidence only blocks explicit Evidence posts -- ordinary replies stay postable.'; tests='Pure model tests for shape, source-chain status enum, risk enum; receipt chip rendering tests.' },
    @{ code='EV-002'; title='Source-chain popover'; epic='epic:evidence'; priority='priority:p0'; effort='effort:m'; release='release:6.6'; goal='One-click tool to ask or inspect: Where did this claim come from? States: No source -> Ask for source. Source no quote -> Ask for quote. Both -> Inspect receipt. Broken -> Source trail is weak. Primary present -> Source trail anchored.'; accept='- Source-chain node uses dotted ring and teal.|- Action inserts composer preset; never accuses.|- Popover never treats popularity as evidence.|- User can attach source later.'; tests='' },
    @{ code='EV-003'; title='Evidence debt tracker'; epic='epic:evidence'; priority='priority:p1'; effort='effort:l'; release='release:6.6'; goal='Make unresolved evidence obligations visible as gameplay debt. Debt types: source, quote, scope example, definition, mechanism, counterexample, primary record. Display: debt chip on node, debt count in sidecar, debt badges on branch line, resolve debt quick action.'; accept='- Debt is per move, not global.|- Can be answered by later moves.|- Does not declare original point false.|- Influences strength visuals, not truth labels.'; tests='' },
    @{ code='EV-004'; title='Evidence symmetry with game rules'; epic='epic:evidence'; priority='priority:p1'; effort='effort:m'; release='release:6.6'; goal='Visual system and rules reinforce each other. Mapping: source_chain -> source trail chip + dotted edge; evidence -> receipt chip + hex shape; scope -> bracket icon; definition -> key-term icon; logic -> chain icon; causal -> arrow icon; anti_amplification -> crowd-slash icon; synthesis_ready -> merge icon; max_depth_reached -> stalemate band.'; accept='- Internal codes converted to plain language.|- Normal users never see raw validation codes.|- Semantic annotations become gameplay affordances.'; tests='Assert no internal snake_case codes leak to user-facing strings.' },
    @{ code='SW-001'; title='Strong vs weak talking point bands'; epic='epic:strength-weakness'; priority='priority:p0'; effort='effort:m'; release='release:6.5'; goal='Make strong and weak talking points visually distinguishable. Existing seven bands stay but normal-user copy is softened: Pretty wrong -> Needs work; Slightly wrong -> Thin; Neutral -> Neutral; Slightly right -> Some support; Maybe right but misguided -> Has a point, but risky; Pretty right -> Well supported; Completely right -> Strongly supported.'; accept='- Timeline uses simplified labels.|- Stack/Cards can show richer seven-band label.|- No winner/loser/truth label.|- Strength uses shape/stroke/texture, not only color.'; tests='Soft-label mapping unit tests; ban-list test that no truth/winner copy survives in any user-facing string.' },
    @{ code='SW-002'; title='Heat, momentum, trend without truth claims'; epic='epic:strength-weakness'; priority='priority:p1'; effort='effort:m'; release='release:6.6'; goal='Show which parts of a debate are active, unresolved, or heating up. Inputs: move count, recent activity, branch depth, unresolved source/evidence debt, repeated axis pressure, no-rebuttal state, synthesis-ready state.'; accept='- Heat never means correctness.|- Popularity never becomes evidence.|- Hot segment uses activity/friction copy.|- Quiet rooms framed as easy entry opportunities.'; tests='' },
    @{ code='IX-001'; title='Timeline zoom and density modes'; epic='epic:interaction'; priority='priority:p1'; effort='effort:l'; release='release:6.6'; goal='Modes: Compact (dots, label on active), Standard (shapes + short labels), Detailed (shapes + badges + snippets), Branch focus.'; accept='- 5-message timeline is not sparse or boring.|- 300-message timeline remains navigable.|- Zoom state persists within room session.'; tests='' },
    @{ code='IX-002'; title='Timeline mini-map overview'; epic='epic:interaction'; priority='priority:p2'; effort='effort:l'; release='release:6.7'; goal='For long debates, show a tiny overview rail with viewport window. Jump to root/latest/hot zone/branch.'; accept='- Uses heat/branch markers.|- Does not crowd mobile UI.'; tests='' },
    @{ code='IX-003'; title='Keyboard and accessibility navigation'; epic='epic:interaction'; priority='priority:p1'; effort='effort:m'; release='release:6.7'; goal='Make timeline playable by keyboard, screen readers, and mobile touch.'; accept='- Arrow L/R moves active node.|- Home/End -> root/latest on web.|- Buttons have accessibility roles and selected states.|- Nodes expose type, ordinal, strength, branch, active state.'; tests='Accessibility role plus state coverage tests.' },
    @{ code='PR-001'; title='My preferences popout'; epic='epic:profile'; priority='priority:p1'; effort='effort:m'; release='release:6.7'; goal='Lightweight preferences without leaving the game. Fields: display name, avatar preview, contact email display/update path, notification preference stub, default room entry preference, visual density, color accessibility mode, reduce motion, default side label preference.'; accept='- Opens as popout/drawer.|- Does not expose role escalation.|- Does not require admin surface.|- No secrets or hidden auth fields.'; tests='' },
    @{ code='PR-002'; title='Profile tag popout'; epic='epic:profile'; priority='priority:p2'; effort='effort:m'; release='release:6.7'; goal='Users can add a limited number of profile tags that shape identity lightly. Allowed: topic interests, debate style, availability, accessibility preference. Disallowed: protected-class targeting, party-affiliation requirement, expert without verification, hostile labels, ideology/personality scoring.'; accept='- Tags are optional.|- Limit visible tags to 3-5.|- Tags do not affect truth/score.|- Tags do not change validation gates.'; tests='Validation-gate immutability test; tag-vocabulary safety test.' },
    @{ code='PR-003'; title='Avatar upload policy and storage'; epic='epic:profile'; priority='priority:p2'; effort='effort:l'; release='release:6.7'; goal='Allow avatar photos while controlling storage, privacy, and safety. Recommended policy: bucket profile-avatars, max 2 MB, jpg/png/webp, resize 256x256 + 64x64 thumb, public-read opt-in else signed, strip EXIF/metadata pre-upload, default generated avatar.'; accept='- User can upload/change/remove avatar.|- Avatar URL not user-editable as raw text.|- Upload validates MIME and size.|- No service-role in client.|- RLS/storage policy prevents arbitrary overwrite.'; tests='' },
    @{ code='PR-004'; title='Contact information update'; epic='epic:profile'; priority='priority:p2'; effort='effort:l'; release='release:6.7'; goal='Allow users to see limited contact info and update it safely. Scope: display current email; Change email flow uses Supabase auth update, not profile-table mutation alone; show verification pending state; do not expose user id except masked/debug; display name separate from email.'; accept='- No role/id/email privilege escalation through profile update payload.|- Email update follows auth provider flow.'; tests='' },
    @{ code='HOST-001'; title='Dev hosting architecture for cdiscourse.com/dev'; epic='epic:hosting'; priority='priority:p0'; effort='effort:l'; release='release:6.8'; goal='Host Expo web app at https://cdiscourse.com/dev. Path-based deployment is riskier than subdomain. Spike both options: A) dev.cdiscourse.com (recommended fallback). B) cdiscourse.com/dev via reverse proxy rewrite + SPA fallback.'; accept='- Chosen URL loads app.|- Direct refresh on nested routes works.|- Static assets resolve.|- Supabase public URL/key from safe public env only.|- No service-role or API keys.|- Console has no 404s.'; tests='' },
    @{ code='HOST-002'; title='Dev environment banner and safety boundary'; epic='epic:hosting'; priority='priority:p0'; effort='effort:s'; release='release:6.8'; goal='Public dev deployment must be visibly dev/test. Banner CDiscourse Dev, commit hash/build version, Test data may be reset notice, Report issue link, bot/test rooms clearly labeled.'; accept='- Dev banner visible.|- No production-confusing copy.|- Bot/test rooms visually marked.'; tests='' },
    @{ code='HOST-003'; title='Deployment smoke checklist'; epic='epic:hosting'; priority='priority:p0'; effort='effort:s'; release='release:6.8'; goal='Define exact cdiscourse.com/dev smoke test: login/signup, gallery loads, duplicate generated rooms collapsed, open room to Timeline, observer rail collapsed, explicit join side, post a move, Timeline-Cards toggle, evidence popover renders, preferences popout opens, avatar default renders, no console 404s, no service-role usage, no raw internal validation codes.'; accept='- Checklist documented.|- Each item has clear pass/fail.'; tests='' },
    @{ code='GAL-001'; title='Upgrade gallery sections into scrum-like play lanes'; epic='epic:gallery'; priority='priority:p1'; effort='effort:m'; release='release:6.6'; goal='Let users choose a debate by what kind of move they want to make. Enhanced sections: Jump in now, Needs first rebuttal, Source trail fights, Evidence needed, Definition fights, Logic traps, Tangents/branches, Almost synthesis, Quiet beginner rooms, My active rooms.'; accept='- Cards grouped by deterministic model.|- User can filter by desired action.|- Generated/test duplicate rooms remain visually collapsed.|- Heat framed as activity/friction.'; tests='' },
    @{ code='GAL-002'; title='Entry cards with first suggested move'; epic='epic:gallery'; priority='priority:p1'; effort='effort:m'; release='release:6.6'; goal='Each gallery card should suggest a simple first action: Be the first rebuttal, Ask for the source, Challenge the mechanism, Narrow the claim, Offer synthesis, Watch first, Join when ready.'; accept='- Hint derived from model fields, not AI call.|- Hint maps to quick action in rail.|- Hint is short and plain-language.|- No raw internal codes.'; tests='' },
    @{ code='RULE-001'; title='Semantic rule-to-UI map'; epic='epic:rules-ux'; priority='priority:p1'; effort='effort:m'; release='release:6.6'; goal='Single mapping from rule/semantic codes to user-facing tools. source_chain -> Ask for the source. evidence_debt -> Needs receipts. scope -> Narrow the claim. definition -> Define the term. logic -> Challenge the inference. causal -> Challenge the mechanism. anti_amplification -> Popularity is not proof. synthesis_ready -> Offer synthesis.'; accept='- toPlainLanguage maps every code used in timeline/sidecar.|- Unknown snake_case codes suppressed in normal UI.|- Tests assert no internal code leaks.'; tests='Code-leak ban test across timeline plus sidecar rendering.' },
    @{ code='RULE-002'; title='Evidence symmetry between validation and visuals'; epic='epic:rules-ux'; priority='priority:p1'; effort='effort:m'; release='release:6.6'; goal='Rules do not just block or warn -- they create gameplay affordances. Weak topic -> May be drifting chip; parent nonresponsive -> Reconnect to parent suggestion; missing source -> source-chain action; missing quote -> quote request; scope risk -> narrow action; definition ambiguity -> clarify/define.'; accept='- Warning becomes a suggested move.|- Suggested move is one click from timeline.|- Ordinary replies remain postable.'; tests='' },
    @{ code='AN-001'; title='Deterministic board diagnostics'; epic='epic:analytics'; priority='priority:p2'; effort='effort:m'; release='release:6.7'; goal='Pure-model dev/debug board readout: hot zones, unresolved axes, strong/weak counts, evidence debt count, branch count, synthesis-ready count, no-rebuttal count.'; accept='- Pure deterministic model.|- No xAI/Anthropic calls.|- Useful for UI tests and debug only.'; tests='' },
    @{ code='AN-002'; title='Visual QA snapshots'; epic='epic:analytics'; priority='priority:p2'; effort='effort:m'; release='release:6.8'; goal='Fixture timelines for visual review: no rebuttal, straight 10-move chain, source-chain fight, evidence-heavy branch, tangent/kink branch, synthesis path, 250-node stress board, avatar/profile display.'; accept='- Fixture model tests pass.|- Browser visual checklist references fixtures.'; tests='' },
    @{ code='PM-001'; title='Create docs/ux-ui-project-board.md'; epic='epic:project-mgmt'; priority='priority:p0'; effort='effort:s'; release='release:6.5'; goal='Canonical roadmap doc.'; accept='- Document exists.|- References Stage 6.2/6.3/6.4 as baseline.|- Does not claim unbuilt features are done.'; tests=''; status='Done' },
    @{ code='PM-002'; title='Add Now/Next/Later tracker to docs/current-status.md'; epic='epic:project-mgmt'; priority='priority:p1'; effort='effort:s'; release='release:6.5'; goal='Make docs/current-status.md show the active UX board stage.'; accept='- Current stage identifies next UX target.|- Completed stages remain historically accurate.|- Test count updated only after actual implementation.'; tests='' }
)

$tempDir = Join-Path $env:TEMP "cd-roadmap-issues"
if (-not (Test-Path $tempDir)) { New-Item -ItemType Directory -Path $tempDir | Out-Null }
$created = 0
$failed = 0
$results = @()

foreach ($c in $cards) {
    $title = "$($c.code) - $($c.title)"
    $labels = "$($c.priority),$($c.effort),$($c.epic),$($c.release),area:roadmap"
    $acceptLines = $c.accept -replace '\|', "`n"
    $body = "**Epic:** $($c.epic.Replace('epic:',''))  `n**Priority:** $($c.priority.Replace('priority:',''))  `n**Effort:** $($c.effort.Replace('effort:',''))  `n**Release:** $($c.release.Replace('release:',''))`n`n## Goal`n$($c.goal)`n`n## Acceptance criteria`n$acceptLines"
    if ($c.tests) { $body += "`n`n## Tests`n$($c.tests)" }
    if ($c.status -eq 'Done') { $body += "`n`n---`n**Status:** Done. See docs/ux-ui-project-board.md." }
    $body += "`n`n---`nSee [``docs/ux-ui-project-board.md``](docs/ux-ui-project-board.md) for full context, dependencies, and the rest of the roadmap."

    $bodyFile = Join-Path $tempDir ("$($c.code).md")
    Set-Content -Path $bodyFile -Value $body -Encoding utf8

    Write-Output "Creating $($c.code)..."
    $issueUrl = & $gh issue create --title $title --body-file $bodyFile --label $labels 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Output "  FAILED $($c.code): $issueUrl"
        $failed++
        continue
    }
    $issueUrl = ($issueUrl | Where-Object { $_ -match '^https://' }) | Select-Object -First 1
    Write-Output "  $issueUrl"

    $addOut = & $gh project item-add $projectNumber --owner $projectOwner --url $issueUrl 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Output "  add-to-project FAILED: $addOut"
    }
    $results += [pscustomobject]@{ code=$c.code; url=$issueUrl }
    $created++
}

Write-Output ""
Write-Output "=== Summary ==="
Write-Output "Created: $created"
Write-Output "Failed: $failed"
Write-Output ""
$results | Format-Table -AutoSize
