import type {
  ConstitutionVersion,
  ConstitutionRule,
  ConstitutionTagDef,
  ConstitutionFlagDef,
} from './types';
import { RULE_CODES, FLAG_CODES, TAG_CODES } from './types';

export const CONSTITUTION_V1_ID = 'c1d00001-0000-0000-0000-000000000001';

export const constitutionVersion: ConstitutionVersion = {
  id: CONSTITUTION_V1_ID,
  slug: 'constitution-v1',
  version: '1.0.0',
  title: 'Constitution v1',
  active: true,
};

export const constitutionRules: ConstitutionRule[] = [
  // ── C-STRUCT-001 ─────────────────────────────────────────────
  {
    id: 'r-struct-001',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.PARENT_REQUIRED,
    title: 'Parent required',
    description: 'Non-thesis arguments must have a parent.',
    ruleType: 'structure',
    severity: 'blocking',
    params: {},
    enabled: true,
  },
  {
    id: 'r-struct-002',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.ROOT_TYPE_ALLOWED,
    title: 'Root type allowed',
    description: 'Only thesis or claim arguments may be posted at root level (no parent).',
    ruleType: 'structure',
    severity: 'blocking',
    params: { allowedRootTypes: ['thesis', 'claim'] },
    enabled: true,
  },

  // ── C-TRANSITION-001 ─────────────────────────────────────────
  {
    id: 'r-transition-thesis',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.TRANSITION_THESIS,
    title: 'Thesis transitions',
    description: 'Allowed child types for a thesis parent.',
    ruleType: 'transition',
    severity: 'blocking',
    params: { allowedChildren: ['claim', 'rebuttal', 'evidence', 'clarification_request'] },
    enabled: true,
  },
  {
    id: 'r-transition-claim',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.TRANSITION_CLAIM,
    title: 'Claim transitions',
    description: 'Allowed child types for a claim parent.',
    ruleType: 'transition',
    severity: 'blocking',
    params: { allowedChildren: ['evidence', 'rebuttal', 'clarification_request', 'concession'] },
    enabled: true,
  },
  {
    id: 'r-transition-rebuttal',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.TRANSITION_REBUTTAL,
    title: 'Rebuttal transitions',
    description: 'Allowed child types for a rebuttal parent.',
    ruleType: 'transition',
    severity: 'blocking',
    params: {
      allowedChildren: ['counter_rebuttal', 'evidence', 'clarification_request', 'concession'],
    },
    enabled: true,
  },
  {
    id: 'r-transition-counter-rebuttal',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.TRANSITION_COUNTER_REBUTTAL,
    title: 'Counter-rebuttal transitions',
    description: 'Allowed child types for a counter_rebuttal parent.',
    ruleType: 'transition',
    severity: 'blocking',
    params: { allowedChildren: ['rebuttal', 'evidence', 'clarification_request', 'concession'] },
    enabled: true,
  },
  {
    id: 'r-transition-evidence',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.TRANSITION_EVIDENCE,
    title: 'Evidence transitions',
    description: 'Allowed child types for an evidence parent.',
    ruleType: 'transition',
    severity: 'blocking',
    params: { allowedChildren: ['clarification_request', 'rebuttal'] },
    enabled: true,
  },
  {
    id: 'r-transition-clarification-request',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.TRANSITION_CLARIFICATION_REQUEST,
    title: 'Clarification request transitions',
    description: 'Allowed child types for a clarification_request parent.',
    ruleType: 'transition',
    severity: 'blocking',
    params: { allowedChildren: ['claim', 'evidence'] },
    enabled: true,
  },
  {
    id: 'r-transition-concession',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.TRANSITION_CONCESSION,
    title: 'Concession transitions',
    description: 'Allowed child types for a concession parent.',
    ruleType: 'transition',
    severity: 'blocking',
    params: { allowedChildren: ['synthesis'] },
    enabled: true,
  },
  {
    id: 'r-transition-synthesis',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.TRANSITION_SYNTHESIS,
    title: 'Synthesis transitions',
    description: 'Allowed child types for a synthesis parent.',
    ruleType: 'transition',
    severity: 'blocking',
    params: { allowedChildren: ['claim', 'clarification_request'] },
    enabled: true,
  },

  // ── C-TOPIC-001 ───────────────────────────────────────────────
  {
    id: 'r-topic-001',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.TOPIC_SATISFACTION_LEXICAL,
    title: 'Topic satisfaction (lexical)',
    description: 'Argument body must share sufficient term overlap with the argument resolution.',
    ruleType: 'topic_satisfaction',
    severity: 'warning',
    params: { threshold: 0.25, offTopicThreshold: 0.1 },
    enabled: true,
  },

  // ── C-EVIDENCE-001 ────────────────────────────────────────────
  {
    id: 'r-evidence-001',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.EVIDENCE_SOURCE_REQUIRED,
    title: 'Evidence source required',
    description: 'Evidence arguments must include at least one attached source.',
    ruleType: 'evidence',
    severity: 'blocking',
    params: {},
    enabled: true,
  },

  // ── C-LENGTH-001 ──────────────────────────────────────────────
  {
    id: 'r-length-001',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.LENGTH_BODY,
    title: 'Body length bounds',
    description: 'Argument body must be between minChars and maxChars.',
    ruleType: 'length',
    severity: 'blocking',
    params: { minChars: 20, maxChars: 2000 },
    enabled: true,
  },

  // ── C-CIVILITY-001 ────────────────────────────────────────────
  {
    id: 'r-civility-001',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.CIVILITY_HEURISTIC,
    title: 'Civility heuristic',
    description: 'Flags likely personal attacks or profanity for admin review.',
    ruleType: 'civility',
    severity: 'review',
    params: {},
    enabled: true,
  },

  // ── C-RAIL-001 ────────────────────────────────────────────────
  {
    id: 'r-rail-001',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.PARENT_RESPONSIVENESS_LEXICAL,
    title: 'Parent responsiveness',
    description:
      'Reply arguments must have lexical overlap with the parent or provide a target_excerpt. Hard blocks only at essentially zero overlap.',
    ruleType: 'rails',
    severity: 'review',
    params: {
      appliesTo: ['rebuttal', 'counter_rebuttal', 'evidence', 'clarification_request', 'concession', 'synthesis'],
      hardBlockThreshold: 0.05,
      warningThreshold: 0.15,
    },
    enabled: true,
  },

  // ── C-RAIL-002 ────────────────────────────────────────────────
  {
    id: 'r-rail-002',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.DISAGREEMENT_AXIS_REQUIRED,
    title: 'Disagreement axis required',
    description:
      'Rebuttals and counter-rebuttals must declare at least one disagreement-axis tag so the nature of the dispute is explicit.',
    ruleType: 'rails',
    severity: 'warning',
    params: {
      appliesTo: ['rebuttal', 'counter_rebuttal'],
      axisTagCodes: [
        'fact_disagreement', 'definition_disagreement', 'causal_disagreement',
        'value_disagreement', 'evidence_challenge', 'logic_challenge', 'scope_challenge',
      ],
    },
    enabled: true,
  },

  // ── C-RAIL-003 ────────────────────────────────────────────────
  {
    id: 'r-rail-003',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.CONCESSION_INTEGRITY,
    title: 'Concession integrity',
    description:
      'A concession must target a specific parent point and include a concession marker. Introducing an unrelated dispute via "but/however" creates a concession_evasion_possible flag.',
    ruleType: 'rails',
    severity: 'review',
    params: {
      appliesTo: ['concession', 'synthesis'],
      concessionMarkers: [
        'i concede', 'i grant', 'i agree with', 'that point is valid',
        'you are right', "you're right", 'fair point', 'i acknowledge',
      ],
      evasionPatterns: ['\\bbut\\b', '\\bhowever\\b', '\\bthat said\\b', '\\bnevertheless\\b'],
      evasionParentOverlapThreshold: 0.1,
    },
    enabled: true,
  },

  // ── C-RAIL-004 ────────────────────────────────────────────────
  {
    id: 'r-rail-004',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.CLARIFICATION_PURITY,
    title: 'Clarification purity',
    description:
      'Clarification requests should ask for a definition, source, scope, or missing premise. Disguised rebuttals with loaded accusations create a loaded_clarification_possible flag.',
    ruleType: 'rails',
    severity: 'review',
    params: {
      appliesTo: ['clarification_request'],
      loadedPatterns: [
        '\\byou obviously\\b', '\\byou clearly\\b', '\\byou always\\b',
        '\\byou never\\b', '\\byou (are|were) wrong\\b', '\\byou (are|were) lying\\b',
      ],
    },
    enabled: true,
  },

  // ── C-RAIL-005 ────────────────────────────────────────────────
  {
    id: 'r-rail-005',
    constitutionId: CONSTITUTION_V1_ID,
    code: RULE_CODES.FACT_CONFUSION_CHANNEL,
    title: 'Fact confusion channel',
    description:
      'Advisory flag when a reply appears to dispute a factual premise but also uses uncertainty language or source-request tags. Not a misconduct flag.',
    ruleType: 'rails',
    severity: 'info',
    params: {
      uncertaintyPatterns: [
        '\\bmaybe\\b', '\\bperhaps\\b', '\\bi think\\b', '\\buncertain\\b',
        '\\bnot sure\\b', '\\bcould be\\b', '\\bwhat is the source\\b',
        '\\bdo you have evidence\\b', '\\bcan you cite\\b',
      ],
      triggerTags: ['evidence_challenge', 'source_request'],
    },
    enabled: true,
  },
];

export const tagDefinitions: ConstitutionTagDef[] = [
  {
    code: TAG_CODES.CLAIM,
    label: 'Claim',
    description: 'A direct assertion that supports or challenges the resolution.',
    category: 'argument',
    allowedArgumentTypes: ['thesis', 'claim'],
    enabled: true,
  },
  {
    code: TAG_CODES.REBUTTAL,
    label: 'Rebuttal',
    description: 'A direct challenge to the parent argument.',
    category: 'argument',
    allowedArgumentTypes: ['rebuttal'],
    enabled: true,
  },
  {
    code: TAG_CODES.COUNTER_REBUTTAL,
    label: 'Counter-rebuttal',
    description: 'A defense against a rebuttal.',
    category: 'argument',
    allowedArgumentTypes: ['counter_rebuttal'],
    enabled: true,
  },
  {
    code: TAG_CODES.EVIDENCE,
    label: 'Evidence',
    description: 'Empirical data, citation, or study supporting a claim.',
    category: 'support',
    allowedArgumentTypes: ['evidence'],
    enabled: true,
  },
  {
    code: TAG_CODES.SOURCE_REQUEST,
    label: 'Source request',
    description: 'Requesting a citation or source for a claim.',
    category: 'meta',
    allowedArgumentTypes: ['clarification_request'],
    enabled: true,
  },
  {
    code: TAG_CODES.CLARIFICATION,
    label: 'Clarification',
    description: 'Asking for clarification of scope, terms, or intent.',
    category: 'meta',
    allowedArgumentTypes: ['clarification_request'],
    enabled: true,
  },
  {
    code: TAG_CODES.CONCESSION,
    label: 'Concession',
    description: 'Partially or fully conceding a point.',
    category: 'resolution',
    allowedArgumentTypes: ['concession'],
    enabled: true,
  },
  {
    code: TAG_CODES.SYNTHESIS,
    label: 'Synthesis',
    description: 'Integrating prior points into a new framing.',
    category: 'resolution',
    allowedArgumentTypes: ['synthesis'],
    enabled: true,
  },
  {
    code: TAG_CODES.SCOPE_CHALLENGE,
    label: 'Scope challenge',
    description: 'Challenging the scope or framing of the argument.',
    category: 'meta',
    allowedArgumentTypes: ['thesis', 'claim', 'rebuttal'],
    enabled: true,
  },

  // ── Disagreement-axis tags (C-RAIL-002) ───────────────────────
  {
    code: TAG_CODES.FACT_DISAGREEMENT,
    label: 'Fact disagreement',
    description: 'Disputes a factual claim the parent makes.',
    category: 'disagreement_axis',
    allowedArgumentTypes: ['rebuttal', 'counter_rebuttal'],
    enabled: true,
  },
  {
    code: TAG_CODES.DEFINITION_DISAGREEMENT,
    label: 'Definition disagreement',
    description: 'Disputes the meaning of a key term in the parent.',
    category: 'disagreement_axis',
    allowedArgumentTypes: ['rebuttal', 'counter_rebuttal'],
    enabled: true,
  },
  {
    code: TAG_CODES.CAUSAL_DISAGREEMENT,
    label: 'Causal disagreement',
    description: 'Disputes the causal relationship the parent asserts.',
    category: 'disagreement_axis',
    allowedArgumentTypes: ['rebuttal', 'counter_rebuttal'],
    enabled: true,
  },
  {
    code: TAG_CODES.VALUE_DISAGREEMENT,
    label: 'Value disagreement',
    description: 'Disputes the normative premise or weight assigned to a value.',
    category: 'disagreement_axis',
    allowedArgumentTypes: ['rebuttal', 'counter_rebuttal'],
    enabled: true,
  },
  {
    code: TAG_CODES.EVIDENCE_CHALLENGE,
    label: 'Evidence challenge',
    description: 'Challenges the quality, relevance, or sourcing of evidence in the parent.',
    category: 'disagreement_axis',
    allowedArgumentTypes: ['rebuttal', 'counter_rebuttal', 'clarification_request'],
    enabled: true,
  },
  {
    code: TAG_CODES.LOGIC_CHALLENGE,
    label: 'Logic challenge',
    description: 'Challenges the inferential step from premise to conclusion in the parent.',
    category: 'disagreement_axis',
    allowedArgumentTypes: ['rebuttal', 'counter_rebuttal'],
    enabled: true,
  },
];

export const flagDefinitions: ConstitutionFlagDef[] = [
  {
    code: FLAG_CODES.OFF_TOPIC,
    label: 'Off-topic',
    description: 'Argument body has very low lexical overlap with the resolution.',
    severity: 'blocking',
    defaultStatus: 'open',
    autoReviewThreshold: null,
    enabled: true,
  },
  {
    code: FLAG_CODES.WEAK_TOPIC,
    label: 'Weak topic satisfaction',
    description: 'Argument body has below-threshold overlap with the resolution.',
    severity: 'warning',
    defaultStatus: 'open',
    autoReviewThreshold: null,
    enabled: true,
  },
  {
    code: FLAG_CODES.MISSING_PARENT,
    label: 'Missing parent',
    description: 'Non-thesis argument lacks a parent.',
    severity: 'blocking',
    defaultStatus: 'open',
    autoReviewThreshold: null,
    enabled: true,
  },
  {
    code: FLAG_CODES.INVALID_TRANSITION,
    label: 'Invalid transition',
    description: 'Argument type is not allowed under its parent type.',
    severity: 'blocking',
    defaultStatus: 'open',
    autoReviewThreshold: null,
    enabled: true,
  },
  {
    code: FLAG_CODES.EVIDENCE_REQUIRED,
    label: 'Evidence source required',
    description: 'Evidence argument must include at least one source.',
    severity: 'blocking',
    defaultStatus: 'open',
    autoReviewThreshold: null,
    enabled: true,
  },
  {
    code: FLAG_CODES.CIVILITY_RISK,
    label: 'Civility risk',
    description: 'Possible incivility detected by heuristic.',
    severity: 'review',
    defaultStatus: 'needs_review',
    autoReviewThreshold: null,
    enabled: true,
  },
  {
    code: FLAG_CODES.AD_HOMINEM,
    label: 'Possible ad hominem',
    description: 'Personal attack pattern detected.',
    severity: 'review',
    defaultStatus: 'needs_review',
    autoReviewThreshold: null,
    enabled: true,
  },
  {
    code: FLAG_CODES.DUPLICATE,
    label: 'Possible duplicate',
    description: 'High textual similarity to an existing sibling argument.',
    severity: 'warning',
    defaultStatus: 'open',
    autoReviewThreshold: null,
    enabled: true,
  },
  {
    code: FLAG_CODES.EXCESSIVE_LENGTH,
    label: 'Excessive length',
    description: 'Argument body exceeds the maximum character limit.',
    severity: 'blocking',
    defaultStatus: 'open',
    autoReviewThreshold: null,
    enabled: true,
  },
  {
    code: FLAG_CODES.UNCLEAR_CLAIM,
    label: 'Unclear claim',
    description: 'Claim body is too short or vague to evaluate.',
    severity: 'warning',
    defaultStatus: 'open',
    autoReviewThreshold: null,
    enabled: true,
  },
  {
    code: FLAG_CODES.MOD_REVIEW,
    label: 'Admin review needed',
    description: 'Flagged for admin review.',
    severity: 'review',
    defaultStatus: 'needs_review',
    autoReviewThreshold: null,
    enabled: true,
  },

  // ── Rails flags (C-RAIL-001–005) ──────────────────────────────
  {
    code: FLAG_CODES.PARENT_NONRESPONSIVE,
    label: 'Not responsive to parent',
    description: 'Argument has essentially no lexical connection to its parent.',
    severity: 'blocking',
    defaultStatus: 'open',
    autoReviewThreshold: null,
    enabled: true,
  },
  {
    code: FLAG_CODES.TANGENT_SHIFT,
    label: 'Possible tangent shift',
    description: 'Argument has low connection to its parent and may be drifting off-topic.',
    severity: 'warning',
    defaultStatus: 'open',
    autoReviewThreshold: null,
    enabled: true,
  },
  {
    code: FLAG_CODES.CONCESSION_EVASION,
    label: 'Possible concession evasion',
    description:
      'Concession introduces a new unrelated dispute after a "but/however" with low parent overlap.',
    severity: 'review',
    defaultStatus: 'needs_review',
    autoReviewThreshold: null,
    enabled: true,
  },
  {
    code: FLAG_CODES.LOADED_CLARIFICATION,
    label: 'Possible loaded clarification',
    description: 'Clarification request may be phrased as a disguised rebuttal or accusation.',
    severity: 'review',
    defaultStatus: 'needs_review',
    autoReviewThreshold: null,
    enabled: true,
  },
  {
    code: FLAG_CODES.FACT_CONFUSION,
    label: 'Possible fact confusion',
    description:
      'Argument disputes a factual premise with uncertainty language or a source request. Advisory only — not a misconduct flag.',
    severity: 'info',
    defaultStatus: 'open',
    autoReviewThreshold: null,
    enabled: true,
  },
];
